### ISSUE TITLE
Why doesn't Runner Deployment support node affinity?

### ISSUE THREAD

**Issue by yutachaos** [actions-runner-controller/actions-runner-controller#1033]
**Is your feature request related to a problem? Please describe.**
Using Runner Deployment, I want to run one Runner on demand instance and another Runner on spot instance.
RunnerSet seems to support affinity, but Runner Deployment does not seem to support affinity.

**Describe the solution you'd like**
Runner Deployment support affinity.

**Describe alternatives you've considered**
Use Runnerset.

**Additional context**
I didn't understand the difference between RunnerSets and RunnerDeployment, so I would like to know how to use them differently..

**Comment by mumoshu** [comment]
@yutachaos Hey!

> Runner Deployment support affinity.

Probably runner.spec.affinity is what you're looking for?

https://github.com/actions-runner-controller/actions-runner-controller/blob/91102c8088b6c01645bbb218b3d4552e774672bf/api/v1alpha1/runner_types.go#L133

> the difference between RunnerSets and RunnerDeployment

FWIW, it's mostly in the implementation details.

RunnerDeployment depends only on K8s pod and we build everything else(RunnerReplicaSet, Runner CRDs, their controllers, etc) from the ground up so that we are sure there will be only features and functionalities we'd need for maintaining self-hosted runners on K8s.

RunnerSet has been added later than Runnerdeployment and it is based on K8s StatefulSet. It basically works by mapping the pod template and the PVC template in the RunnerSet resource to a K8s statefulset. It "seems" to work well so far and it has the support for PVC, which is missing in the RunnerDeployment.

**Comment by yutachaos** [comment]
I missed it. Thank you!

https://github.com/actions-runner-controller/actions-runner-controller/blob/91102c8088b6c01645bbb218b3d4552e774672bf/api/v1alpha1/runner_types.go#L133
