### ISSUE TITLE
Github runner autoupdate

### ISSUE THREAD

**Issue by jin-ahn** [actions-runner-controller/actions-runner-controller#1053]
**Describe the bug**
Whenever github releases a new version of the the runner, it forces all running runners to update to the new version and restart before it is able to run actions. This is a problem is on k8s when the pod is restarted due to the update trigger, it restarts a fresh container with old version, which creates a restart loop. [https://github.com/actions/runner/issues/485]

Is there a workaround to avoid this issue? If we use the default image for the runnerdeploy, then we're dependent on the summerwind docker image repo updating to the latest version in time. If there's ever a scenario where Summerwind repo isn't updated or for some reason no longer maintained, then we're stuck with a broken restart loop. If we use a custom image, then we still cannot use the summerwind as the base image

**To Reproduce**
Deploy a version of summerwind repo that has older github version.

**Expected behavior**
Github's auto update won't break a k8s runnerdeployment

**Environment (please complete the following information):**
 - Controller Version -  v0.20.4
 - Deployment Method - kubectl yaml

**Comment by mumoshu** [comment]
Also see #888 for potential solution to disable the auto-update at all, and a link to a `actions/runner` issue about enhancing it on GitHub side, not ARC side.

Again,

> we're stuck with a broken restart loop

This shouldn't happen, because we already use `runsvc.sh` provided by `actions/runner` to let the container keep running while auto-update is in-progress.

So I can hardly believe it actually happen.
