### ISSUE TITLE
Runner's pod is not re-created once Runner is updated

### ISSUE THREAD

**Issue by bfanyuk** [actions-runner-controller/actions-runner-controller#1177]
**Describe the bug**
Once I change a resource of kind "Runner", it's corresponding pod is not automatically updated. 
I have to kill the pod manually.

**Checks**

- [x] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

1. Create resource of kind "Runner"
2. Wait until corresponding pod is running
3. Modify env variable or runner labels 

**Actual behavior**
The old pod is still running

**Expected behavior**
The old pod is terminated and new updated pod is created

**Environment (please complete the following information):**
 - Controller Version - don't know how to get this info, maybe some command ?
 - Deployment Method - plain kubernetes yaml file

**Comment by mumoshu** [comment]
@bfanyuk Yep, that's how it's intended to work. ARC v0.21 is halfway towards the ideal state so it still does so sometimes, but a runner should never recreate the runner pod due to runner spec update. Doing so would result in race conditions that can terminate the runner pod prematurely while running a job.

If you definitely need a single runner that can safely replace the underlying pod on update, do use a single replica RunnerDeployment.
