### ISSUE TITLE
Spot instances support

### ISSUE THREAD

**Issue by lukasz-mitka** [actions-runner-controller/actions-runner-controller#1200]
**Is your feature request related to a problem? Please describe.**
I would like to reduce my bill by running GH Actions on spot instances.

**Describe the solution you'd like**
Since spot instance can be taken down anytime it would need some automatic failover without failing workflow/job.

**Describe alternatives you've considered**
None.

**Additional context**
It's not acceptable for me to have to manually retrigger failed job.

I'm fine with it not being doable, just hope someone maybe have some idea.

**Comment by mumoshu** [comment]
Maybe you can build another application that detects workflow jobs that failed prematurely for some reason, and poke a "rerun a failed workflow" API (is there any? 🤔 ) to trigger a rerun.

AWS spot instances only notifies us before 2 minutes it gets terminated so I don't think it's enough time for gracefully terminating runners that are running moderately big jobs (that can easily take minutes to complete).

Thoughts?

**Comment by mumoshu** [comment]
BTW the next version of ARC (0.22.0) should be generally more reliable than previous versions on pod termination, so you may be required less manual reruns for free with that, as long as you use a proper mechanism to propagate spot termination notice to pod termination, e.g. https://github.com/aws/aws-node-termination-handler

**Comment by msessa** [comment]
@lukasz-mitka, in my org we run ARC in a a 100% spot-based EKS cluster, and while it's true that there are no guarantees for availability of spot instances, some precautions can be taken to ensure near-perfect uptime for runners.

My advice in this case would be to make sure you regularly scale-to-zero the ASG where your runner pods are scheduled anytime there are no jobs running (for that we rely on cluster-autoscaler), then make sure to configure your ASG (or EKS NodeGroup) with as many different instance types as you can, preferably from different markets (instance classes) and set your ASG to use [capacity-optimized allocation strategy](https://aws.amazon.com/blogs/compute/introducing-the-capacity-optimized-allocation-strategy-for-amazon-ec2-spot-instances/) to ensure that the most-likely-to-survive instance class is picked every time there's a scale-up.

With this setup I have yet to run in a failed job due to spot termination.

Hope that helps.

**Comment by iahmad-khan** [comment]
you can use GKE node auto provisioning along with configuring the scaleSet to prefer spotVMs when available, NAP will do the rest.
