### ISSUE TITLE
Service name has a duplicated Prefix

### ISSUE THREAD

**Issue by murty549** [actions-runner-controller/actions-runner-controller#1208]
My runner is unable to find webhook service because of weird prefixing of the service.

The output of kubectl get services -n actions: (actions is just the namespace in which I have installed the helm chart)
<img width="953" alt="Bildschirmfoto 2022-03-11 um 18 24 46" src="https://user-images.githubusercontent.com/99815544/157916659-a5aba916-31e0-443a-a3b2-74a1d1b61c56.png">

Environment:
 - Kubectl [v1.22.4]
 - Deployment Method [Helm]
 - Helm Chart Version [0.16.1]
 - GKE Cluster

Here is the error:
<img width="1105" alt="Bildschirmfoto 2022-03-11 um 18 27 41" src="https://user-images.githubusercontent.com/99815544/157917153-fc1d7092-2acc-42dd-9a60-833fa3eb086c.png">

Here are all the installed objects:
<img width="1083" alt="Bildschirmfoto 2022-03-11 um 18 29 25" src="https://user-images.githubusercontent.com/99815544/157917397-3ad317ac-0dcc-4530-ab8c-f4e670a3ed9f.png">

Cannot delete and reinstall everything because its a prod cluster, and I have already tried different namespaces.
Thanks a lot for any sort help!

**Comment by murty549** [comment]
I did not override anything and used the default values in the values.yaml. But the problem is solved because there were some dangling resources in the cluster. There were a bunch of cluster roles and cluster role bindings:
<img width="586" alt="Bildschirmfoto 2022-03-12 um 05 59 30" src="https://user-images.githubusercontent.com/99815544/158004500-a24eabce-2383-442d-bad8-73acb1f159f0.png">
They were not deleted after a helm delete. After I deleted them manually, the prefix was gone and it started to work perfectly.

**Comment by mumoshu** [comment]
@murty549 Hey. Your second screen capture says that there's at least one `mutatingwebhookconfiguration` that points to a K8s service named `actions-runner-controller-webhook` in `actions-runner-system`. But you said you're using `actions` as the namespace to install ARC.

That makes me think that you have two conflicting ARC instances in `actions-runner-system`(maybe this is the older one?) and `actions`. If that's intentional, it isn't supported today.
Just make sure you only have one instance of ARC per cluster. Or just specify the same namespace to run `helm upgrade`.

**Comment by murty549** [comment]
Yes that was the exact problem. Thanks a bunch :D
