### ISSUE TITLE
Runners stuck in Terminated/Terminating state using v0.22

### ISSUE THREAD

**Issue by lolletsoc** [actions-runner-controller/actions-runner-controller#1273]
**Describe the bug**
We upgraded to `0.22` and we saw that runners were getting stuck in both the _Terminating_ and _Terminated_ state. Some of these were stuck for over 3 days. We rolled back to `0.21.1` and the problem was immediately resolved. It seems that some sort of finalizer was getting stuck.

**Expected behavior**
Runners should not get stuck in either Terminating/Terminated states.

**Environment (please complete the following information):**
 - Controller version  = `0.22`
 - Deployment method = `Kustomize`
 - Kubernetes version = `1.21.6`

We're going to set up a test organisation and cluster. We wanted to check in here first, to see if anyone has any immediate ideas or has experienced this themselves.

**Comment by mumoshu** [comment]
@lolletsoc Hey! Not really sure what's exactly happening with all the logs from ARC controllers your K8s manifest YAML files, but my guess is, this can be the same one as @ekarlso has recently encountered. It's fixed in #1264.

Does your cluster have another mutating webhook that injects a container that ARC doesn't know about, to every runner pod?

In @ekarlso's case, it was a mutating webhook that injects `vault-agent` container to every runner pod, which broke the new code path introduced in ARC 0.22.0 that involves `runnerpod-controller` to gracefully terminate runner pods managed by a RunnerDeployment.

**Comment by shivamag00** [comment]
It seems that v0.22.0 has some bug. I faced #1144 with v0.22.0 but not with v0.21.0 (and works fine)

**Comment by mumoshu** [comment]
@shivamag00 Hey! Just curious, but how your issue relates to this issue? Or are you just trying to use this issue as an umbrella issue for every issue found in 0.22.0? 🤔 Then, I'd appreciate it if you could open a dedicated issue so that it's easier to diagnose for me.

**Comment by toast-gear** [comment]
@lolletsoc if you can try bumping to v0.22.2 we think that will resolve this issue, I'm going to close it on the assumption it does, re-open if it doens't with details, logs etc

**Comment by lolletsoc** [comment]
Hey @toast-gear,

We will deploy this tomorrow morning and report back!

**Comment by danxmoran** [comment]
kubernetes/kubernetes#104107 looks related to my issue. I'm not sure if it's the root bug, or if it's just obfuscating the error message we end up seeing.

**Comment by mumoshu** [comment]
@danxmoran Hey! Would you mind opening a dedicated issue for yours with more details? =

**Comment by danxmoran** [comment]
@mumoshu done, see #1307

**Comment by mumoshu** [comment]
@toast-gear I think you reopened this due to @danxmoran's report (which resulted in #1307). As it's fixed now, can we safely close this?
