### ISSUE TITLE
Make it easier to rotate a PAT token

### ISSUE THREAD

**Issue by nitrocode** [actions-runner-controller/actions-runner-controller#1376]
**Is your feature request related to a problem? Please describe.**

I currently have my token stored in ssm. I use a terraform data source to retrieve it, create a kubernetes secret, and then redeploy the helm release. This should work but I always have a runner stuck and need to patch its finalizers to update the runner to use the new token.

**Describe the solution you'd like**

it would be nice if updating the secret for the credential would force the runner to use the new token instead of the old token. 

**Describe alternatives you've considered**

* manual rotation - what I currently do, see steps above
* automate manual steps
* perhaps look into ASCP https://docs.aws.amazon.com/systems-manager/latest/userguide/integrating_csi_driver.html
* or another SKIM to Kubernetes secret tool

**Additional context**
N/A

**Comment by mumoshu** [comment]
@nitrocode Hey!

> This should work but I always have a runner stuck

Why? Did you immediately revoke the old PAT and you didn't "recreate" the actions-runner-controller pods after the secret update, right? You need to either keep the old PAT available until all the ARC pods are eventually restarted with the new secret, or explicitly recreate all the ARC pods so that the new pods get the new GitHub API creds-related envvars from the updated secret.

I thought it's a standard K8s/Helm idiom that you need to include some random-looking hash suffix to the secret name and refer to it from the pod spec so that any update to k8s  secret generated by helm triggers a rolling-update of dependent deployments(in our case it's ARC's controllermanager and github-webhook-server pods). Our chart doesn't follow that idiom yet so you'd need to manually receate pods to let it remount the updated secret into container envvars.

**Comment by nitrocode** [comment]
Ah a unique name for the secret so if the ssm value changes, it will create the secret as a new name, delete the old one, and then uninstall and reinstall the helm chart. However, I imagine we'll still have a stuck runner due to the finalizer. I'll test this out next time we need to rotate the key. Thank you for getting back to me so quickly.

**Comment by mumoshu** [comment]
@nitrocode Hey! Thanks for your confirmation.

> However, I imagine we'll still have a stuck runner due to the finalizer. I'll test this out next time we need to rotate the key
I'd appreciate if you could give it a shot but anyway, I think the fact that it's stuck is the PAT it was using at the moment had no permission to call RemoveRunner GitHub Actions API. But it should be able to do so, as long as the old and the new PATs had the same set of permissions.

That's why I'm suspecting that it's just that you revoke the old PAT too early. Keep the old PAT until the new ARC pods come up with the new PAT, takes the leader-election lock, finishes reconciling various custom resources(runners, runnerreplicasets, runnerdeployments, etc) at startup, you'll finally be able to safely remove the old PAT.

Note, at least, removing the old PAT immediately after `helm upgrade` completion is wrong.

**Comment by nitrocode** [comment]
Unfortunately, this happened because we set an expiration date on the PAT, allowed the date to pass, and then try to rotate the token. If the token is already stale, then would the unique kubernetes secret name make a difference upon rotation?

**Comment by mumoshu** [comment]
@nitrocode Thanks for the update!

> we set an expiration date on the PAT, allowed the date to pass, and then tried to rotate the token

I believe that's wrong in most cases. You should usually retain the old token until the new token is fully deployed hence the old token is no longer used, and invalidate or remove the old one only after that.
If a token is being invalidated automatically on a predefined expiration date, to minimize downtime, the new token should be fully rolled out before the expiration happens.

> If the token is stale, then would a unique kubernetes secret name make a difference upon rotation?

I couldn't get this part. If it's already stale, nothing prevents the ARC instance with the old token from breaking.

Anyway, you'd need to have unique k8s secret names for use with `authSecret.name`(was this helm value key correct? I don't remember) so that a change to the secret name used by ARC would result in K8s rolling-update controller pods.
