### ISSUE TITLE
Unnecessary Dependency Installed in Docker Container

### ISSUE THREAD

**Issue by hi-artem** [actions-runner-controller/actions-runner-controller#1377]
**Describe the bug**

DIND runner installs a number of dependency that seems to be unnecessary and even possibly harmful, for example [netcat](https://github.com/actions-runner-controller/actions-runner-controller/blob/master/runner/Dockerfile.dindrunner#L29) and [telnet](https://github.com/actions-runner-controller/actions-runner-controller/blob/9f254a23937ad54e8a3912ed8c8c59a71bc96f04/runner/Dockerfile.dindrunner#L39).

This binaries shouldn't be installed in the container unless there is a usage for them, in which case the usage should probably be reconsidered (especially for netcat since it is using insecure protocol). The rest of the dependencies should be reviewed and insured that the image doesn't have unnecessary applications installed.

**Comment by mumoshu** [comment]
@hi-artem Hey. Can you somehow verify that those binaries are not present in GitHub-managed runners VM images? If it isn't present there too and ARC works without those two, certainly we don't need those and those can be removed safely.

**Comment by toast-gear** [comment]
https://docs.github.com/enterprise-server@3.5/admin/release-notes#self-hosted-runners-for-github-actions-can-now-disable-automatic-updates GHES 3.5 introduces support for the `--disableupdate` flag

Historically Actions didn't have proper container support and enforced the runner software being always at the latest, neither of these 2 things are true anymore once GHES 3.5 becomes generally avaliable. As a result we should be aiming to provide a slim runner for people to build off instead of a fat runner once GHES 3.5 is generally avaliable + some time for people to upgrade.

**Comment by mumoshu** [comment]
We've removed unnecessary packages from the newly released Ubuntu 22.04 runner images. Let me close this as resolved but please feel free to reopen if necessary!

Related: #2006 #2030
