### ISSUE TITLE
Pull based autoscaling Issue: Runners don't scale down even after setting scaleDownDelaySecondsAfterScaleOut

### ISSUE THREAD

**Issue by rahul-FLS** [actions-runner-controller/actions-runner-controller#1398]
Hello @mumoshu I am testing pull based auto scaling of runners and configured below manifest for HorizontalRunnerAutoscaler

apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
    name: actions-runner
    namespace: actions-runner-system
spec:
  maxReplicas: 5
  minReplicas: 0
  **scaleDownDelaySecondsAfterScaleOut: 30**
  scaleTargetRef:
      name: actions-runner
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - test
   
I want the runners to scale down after 30 seconds but thats not happening rather I see the expirationTime has been cached automatically to 10mins from the time of scale out of 1 runner.

kind: HorizontalRunnerAutoscaler
metadata: 
  creationTimestamp: "2022-04-28T19:42:45Z"
  generation: 4
  name: actions-runner
  namespace: actions-runner-system
  resourceVersion: "2824459"
  uid: e6863d2c-1fbd-4431-a0b3-a0d85845ba08
spec:
  maxReplicas: 5
  metrics:
  - repositoryNames:
    - test
    type: TotalNumberOfQueuedAndInProgressWorkflowRuns
  minReplicas: 0
  scaleDownDelaySecondsAfterScaleOut: 30
  scaleTargetRef:
    name: actions-runner
**status:
  cacheEntries:
  - expirationTime: "2022-04-28T20:44:19Z"
    key: desiredReplicas
    value: 1
  desiredReplicas: 1
  lastSuccessfulScaleOutTime: "2022-04-28T20:34:29Z"**

I see this entry in controller logs too

_**1.6511768944537487e+09	DEBUG	actions-runner-controller.horizontalrunnerautoscaler	Calculated desired replicas of 1	{"horizontalrunnerautoscaler": "actions-runner-system/actions-runner", "suggested": 1, "reserved": 0, "min": 0, "cached": 1, "max": 5}**_

I have no idea from where this cache expiration of 10mins is getting set. Any clues please? 

Many thanks in advance :)

Rahul

**Comment by mumoshu** [comment]
@rahul-FLS Hey. It's configurable via github-api-cache-duration and it has been removed in 0.22.0

https://github.com/actions-runner-controller/actions-runner-controller/commit/55ff4de79aa1bcee6c26a097574b5995f009936e

I'm very hesitant to say something like this because it should be obvious, but- could you please use the bug report form if you think it's a bug?

https://github.com/actions-runner-controller/actions-runner-controller/issues/new/choose

It has fields for useful information like ARC version which should have helped issues like this one. Without those information, it's a guessing game and I can't determine immediately if it's just a usage question that I don't need to handle so fast, or a real bug that needs to be handled in a higher priority.

Also, use Discussions for usage questions! That's why we don't have a "Question" form for issues.
