### ISSUE TITLE
Deleting RunnerDeployment does not delete Runners

### ISSUE THREAD

**Issue by Nuru** [actions-runner-controller/actions-runner-controller#141]
I created some RunnerDeployments. The pods did not register because of permissions issues with the Personal Access Token. So I deleted the RunnerDeployments.

**Expected:**
I expected the Runners and Pods to be deleted promptly after the RunnerDeployment was deleted

**Actual:**
The Runners and Pods remained for over 15 minutes

Version: `summerwind/actions-runner-controller:v0.9.3`

**Comment by igorbrigadir** [comment]
Yeah i got this too, i'm not sure if anything changed since, but it was really awkward to kill those because i had to manually edit the runner in the cluster (i used k9s but `kubectl edit` works too)

you need to remove:

```
finalizers:
  - runner.actions.summerwind.dev
```

from each of the `runner` resources that `kubectl get runners --all-namespaces` will show.

**Comment by mumoshu** [comment]
I thought this has been handled in https://github.com/actions-runner-controller/actions-runner-controller/blob/5309b1c02c3dd23603ca1699cd209d662312c0f0/controllers/runner_controller.go#L110 since even earlier versions of actions-runner-controller. Please submit another issue if this still reproduce!
