### ISSUE TITLE
Passing secrets to runner for use in workflow

### ISSUE THREAD

**Issue by dudicoco** [actions-runner-controller/actions-runner-controller#245]
Hi,

Is it possible to pass secrets as environment variables to the runner which will then be available to the workflow, instead of using github actions secrets?

Thanks

**Comment by mumoshu** [comment]
@dudicoco Hey! Yeah, that should be possible with runner.spec.[envFrom](https://github.com/summerwind/actions-runner-controller/blob/524cf1b3793aeb8ea6280b2c1cd0a9cd55090173/api/v1alpha1/runner_types.go#L51), where you can specify the pair of envvar name and the k8s secret to be used as a runner container's envvar.

**Comment by dudicoco** [comment]
Thanks @mumoshu!
I'll give it a try.

**Comment by dudicoco** [comment]
@mumoshu it worked with `envFrom`, thanks!
However, I wasn't able to pass the environment variable into a container step:
```
      - name: docker echo
        uses: docker://alpine:3.8
        with:
          entrypoint: /bin/echo
          args: ${MY_SECRET}
```

The above doesn't work, any ideas?

**Comment by mumoshu** [comment]
@dudicoco Not sure if it's supported by GitHub Actions but I'd suggest trying `${env.MY_SECRET}`

**Comment by dudicoco** [comment]
Thanks @mumoshu, it is indeed supported using `${{ env.MY_SECRET }}` - https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#env-context.

However, I have already tried that beforehand, and it ends up with an empty string.

**Comment by dudicoco** [comment]
Hi @mumoshu, I was able to do this with `docker run` following to your suggestion here https://github.com/summerwind/actions-runner-controller/issues/246#issuecomment-751963304
```
      - name: docker run
        run: |
          docker run -e MY_SECRET alpine:3.8 echo ${MY_SECRET}
```

It seems that `uses` cannot access the runner's environment variables.

**Comment by ejhayes** [comment]
Hi @mumoshu -- is it possible to reload when secret values are updated?

For example if I have this kind of `RunnerDeployment`:
```
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: example-runner-deployment
spec:
  template:
    spec:
      organization: ****
      env:
        - name: XX_MY_SECRET_XX
          valueFrom:
            secretKeyRef:
              key: XX_SECRET_KEY_XX
              name: my-secret
```

In the above I am above to get the value of `XX_MY_SECRET_XX` from the `my-secret` secret. However, if I make an update to this value I do not see the updated value until the pods restart.

I've been using https://github.com/stakater/Reloader for other projects, but it is tied to the `Deployment` resource and doesn't work with pods or the custom CRDs from this project (possibly related to #133) .

Any thoughts/ideas on how to accomplish this?

**Comment by mumoshu** [comment]
@ejhayes Hey! Unfortunately that's impossible. I tend to use helm or kustomize so that each revision of your secret gets its own name (like `my-secret-<hash>` where `<hash>` differs among different contents of the secrets) so that RunnerDeployment can be updated for the new secret name.

I'm still curious - What's your goal? Is the ability to trigger RunnerDeployment updates from any changes to a specific secret is a must-have for you, or can you just migrate to use helm or kustomize (i.e. its secret generator) for that?

**Comment by ejhayes** [comment]
Thanks for the input here @mumoshu! The goal here would be to do a rolling deployment of the github action runner pods in the event that a secret/configmap changes values. Updating the secret name unfortunately wouldn't work great for my use case.

I am using vault-crd (https://github.com/DaspawnW/vault-crd) to sync values from vault into a kubernetes secret resource. This lets me sync vault configuration into a kubernetes `secret` like this:

```
---
apiVersion: koudingspawn.de/v1
kind: Vault       
metadata:
  name: "secret-name"
spec:
  path: "path/to/secret"
  type: KEYVALUEV2
```

The above would create a secret called `my-secret` that contains all the values from the vault path `path/to/secret`. Any time one of the values in `path/to/secret` changes in vault it is automatically synced to `my-secret`. Since the configuration values are able to change in vault without warning (for example if one of our admins changes a value via the vault API or UI) I want to be able to detect the configuration update and ensure anything dependent on those values is updated/restarted. The reloader tool (https://github.com/stakater/Reloader) is able to do this, but only with `Deployments` (not specific pods):

> Reloader can watch changes in ConfigMap and Secret and do rolling upgrades on Pods with their associated DeploymentConfigs, Deployments, Daemonsets and Statefulsets.

I believe there's a large amount of other use cases aside form this that would benefit from creating action runners from a `deployment` rather than having this controller create and manage the individual pods. From #133:

> The controller can run and be a source of authentication credentials and can monitor the status of pods using standard Kubernetes resources watches without directly owning the Pods. (It already appears to fail to handle replacements of Runner resources correctly, and it is not like the current solution is without other problems, e.g. #62, #141 )
> 
> Projects like kiam manage to securely pass credentials in a client/server architecture. This project is already requiring cert-manager to create internal TLS certificates, it could certainly create client authentication certificates if desired so that it would only serve credentials to its own pods (it would be as secure as it is currently with the primary GitHub credential being in a Kubernetes secret). So the pods can register with the controller when they come up, receive their access token from the controller, and continue to be monitored by the controller and autoscaler pretty much the same as is now. And you would get the advantage of the Kubernetes scheduler managing pod replacement when pods fail or the nodes they are on shut down, among many other benefits of using standard Deployment and ReplicaSet resources.

Either way it sounds like a PR would likely be needed to support this functionality. I can work with this limitation for now, but definitely think it'd be very useful.

**Comment by mumoshu** [comment]
@ejhayes Hey! Thanks for the info.

Yeah, I believe it would be the best if we could use the regular Deployment for runner pods. But it turned out not as easy as I thought - the biggest question for me is, how would I let the runner pods to find the controller's API endpoint for getting the registration token?

In kiam's case, it was `http://169.254.169.254` managed by the iptables rule injected by `kiam`. Adopting this pattern implies that (1) the server needs privileged access to host's iptables and (2) we have no straight-forward way to host two or more groups of runners as the runner controller's API server would have no hint to distinguish which authenticated client is for which GitHub repository/organization(for multi-tenancy).

So I was wondering if the most viable short-term solution to your problem can be enhancing the actions-runner-controller to track changes in specified secrets.

For example, what if you enhanced RunnerDeployment to include `recreateReplicaSetOnChanges: {"secretNames": ["my-secret"]}`, so that it recreates the ReplicaSet so that newly created pods has envvars from the latest secret data?

**Comment by ejhayes** [comment]
@mumoshu yes that seems like it'd definitely work. Could this be for secrets and configmaps, not just secrets?

**Comment by mumoshu** [comment]
@ejhayes Thanks for confirming! Yeah, configmaps should be possible, too.

**Comment by dudicoco** [comment]
@mumoshu I think that would require the controller to have permissions to read k8s secrets, which could be a security concern.

@ejhayes if you're using vault, why not use a more native tool to pull the secrets from vault directly into the pods: https://banzaicloud.com/blog/inject-secrets-into-pods-vault-revisited/

A way to restart the pod is required regardless for k8s secrets though, I just think that if you're using vault it's a shame to sync the secrets into k8s secrets. :)

**Comment by mumoshu** [comment]
> require the controller to have permissions to read k8s secrets

Good point. It should be an optional feature then.

> why not use a more native tool to pull the secrets from vault directly into the pods

I understand that someone prefers using vault sidecars, another prefers solutions similar to externa-secrets/aws-secret-operator + reloader, another prefers using one of `secrets-store-csi-driver-provider`s. And there's no single solution fits everyone.

**Comment by ejhayes** [comment]
@dudicoco very slick. And yes, it is a shame having that info exist in an intermediate location 😆. I'll be checking out your recommendation for sure!

Agree with @mumoshu that there are many different solutions out there. Being able to reload when lookup values change seems more or less a universal need.

**Comment by kuperiu** [comment]
If you're using vault you can use this custom actions. it's using the service account to authenticate to vault so you must setup a k8s backend in vault
https://github.com/kuperiu/vault-k8s-github-action
The enviroment variable will last for the entire job, also by default environment variables are exposed in the GHA logs so this action also mask them from the log
