### ISSUE TITLE
Runner auto update makes the runner crash

### ISSUE THREAD

**Issue by kuperiudazn** [actions-runner-controller/actions-runner-controller#268]
I'm using the controller v0.16.0 with runner v2.275.1. From this morning The runner is autoupdating to v2.276.0
Now when a job start the runner crash. I saw that there's an issue about 2.276.0 https://github.com/summerwind/actions-runner-controller/issues/264. But for now i'm unable to use the runner.

Is there a way to disable the runner's auto update ?

**Comment by callum-tait-pbx** [comment]
I think there are 2 issues going on atm:

1. There is the issues with the externals volume which an issue with this solution fixed by https://github.com/summerwind/actions-runner-controller/pull/253 in theory
2. There is an issue with v2.276.0 itself which is an issue with the runner project https://github.com/actions/runner/issues/925

Being able to stop auto updates would be great and tbh I think a major issue with github actions atm. https://github.com/actions/runner/issues/925 suggests that this isn't behaviour that can be opted out of though and would need the ability to do so added into the runner project itself

**Comment by achedeuzot** [comment]
I didn't find a way of disabling the auto-update but I did manage to restart everything by following the discussion in the PR #253.
See https://github.com/summerwind/actions-runner-controller/issues/264#issuecomment-764549833 

Indeed, being able to prevent auto-updates would be very appreciated so we don't need to quickly fix & patch a critical system such as the build/release 😄
