### ISSUE TITLE
Configuring prometheus metrics

### ISSUE THREAD

**Issue by neillturner** [actions-runner-controller/actions-runner-controller#454]
I can see that there is prometheus metrics support in the code but couldn't figure out how to configure it. 
Can we have some docs on how to do this?

**Comment by vterdunov** [comment]
Hi. Which installation method did you use?
For kustomization I found [this example](https://github.com/summerwind/actions-runner-controller/blob/374105c1f30ce8cc1e54079b432027ff63521463/config/default/kustomization.yaml#L24)

There is a problem If you use helm. For some reason `manager` container in pod listen [localhost](https://github.com/summerwind/actions-runner-controller/blob/master/charts/actions-runner-controller/templates/deployment.yaml#L34)
Also, service for metrics has weird name [auth_proxy_service.yaml](https://github.com/summerwind/actions-runner-controller/blob/374105c1f30ce8cc1e54079b432027ff63521463/config/rbac/auth_proxy_service.yaml#L6)

**Comment by yfried** [comment]
I'm seeing the same problem.
@neillturner did you manage to bypass this?

**Comment by neillturner** [comment]
i've spent several days trying to figure this out. admittedly i'm still learning kubernetes and don't understand RBAC yet
its seems to the only point of the kube-rbac-proxy is to block access to the metric endpoint without any docs on how to authorize yourself. 
I tried going into my prometheus server instance and 
export bearer=token from actions-runner-controller-token secret 
export header=export header="Authorization: Bearer $bearer"

**Comment by mumoshu** [comment]
If you don't use Network Policy at all/don't need to protect your metrics endpoint/your Prometheus endpoint scraper(Prometheus, datadog-agent, etc) doesn't support using the serviceaccount token authn, you can just use unauthenticated metrics endpoint as usual.

The unauthenticated metrics endpoint server should be listening on port 8080, rather than 8443.

Also, trying to scrape against `controller-manager-metrics-service.system` doesn't make sense to me, as what you might usually want is metrics correlated to pods, not k8s services.

**Comment by mumoshu** [comment]
So, the issue seems to be that our chart doesn't support exposing actions-runner-controller pods' 8080 to outside of the pod. Making it configurable via values would make it straightforward.

**Comment by yfried** [comment]
@mumoshu 
I'm happy to create a PR for this

**Comment by yfried** [comment]
@mumoshu  please take a look

**Comment by neillturner** [comment]
thanks
