### ISSUE TITLE
edge: Registration-only runner disappears before runners are up

### ISSUE THREAD

**Issue by mikesplain** [actions-runner-controller/actions-runner-controller#516]
Thanks for the great project! I've been testing out the new scaling to zero and I believe I've found a bug with https://github.com/actions-runner-controller/actions-runner-controller/pull/465.  When runners are at zero and a registration runner is offline, a user pushes a commit or opens a PR, etc. to trigger a scale up with the webhook.  

The runners begin starting up (YAY) but almost immediately the registration runner disappears (BOO).  I think the issue is that it is removed before other runners are active (they're still starting)?  I haven't been able to figure out the issue in the code, there may need to be more logic in https://github.com/actions-runner-controller/actions-runner-controller/pull/465/files#diff-5ec1753568c3eb77cc6c854abf50248883481cd011244012145cd5769e948ad6R119-R128 or so.

Anyway I'll let you know if I can debug further.

**Comment by mumoshu** [comment]
@mikesplain Hey! Thanks for testing the edge version of actions-runner-controller. That's super helpful.

That does seem to be caused by a potential bug in the controller.

My quick recall says that I might have forgotten to let it wait for runners to be up before deleting the registration-only runner, which matches exactly with your thought.

Let me confirm and fix it soon.
