### ISSUE TITLE
Add the ability to pass/grab Runner Registration tokens instead of installing Private Key

### ISSUE THREAD

**Issue by joshua-reddish** [actions-runner-controller/actions-runner-controller#551]
In setting this solution up, our team found that the only way to use a GitHub app with the Controller was too store the private key of our App in the k8s cluster as a secret. We would prefer to be able to provide the runner registration token directly, and on demand, from our own automation. Are there any plans/ is this something we can request to make possible? 

Our ideal scenario would be to be able to provide an API call that the controller uses to grab the token on demand.

Thanks for taking a look, and let me know if there is any more information I can provide!

**Comment by mumoshu** [comment]
@joshua-reddish Hey! Are you literally saying that you're willing to call [create registration token API](https://docs.github.com/en/rest/reference/actions#create-a-registration-token-for-a-repository) on your own, and let the controller to use it to create a run-once runner?

Would you mind sharing us the big picture of what you're trying to build on top of actions-runner-controller?

**Comment by joshua-reddish** [comment]
Hi @mumoshu, thanks for the reply!

The Big Picture: Before we discovered the service being developed in this repo, we had stood up a lambda/API Gateway that used our GitHub apps private key to generate our runner registration tokens on demand, via API. This allowed us to have one GitHub app centrally managed/secured to manage all of our runner token needs.

What I would like to be able to do, is integrate that API into the controller, so that when we scale up or down, the controller just needs to make an API call to get a token, instead of using the private key stored in k8s to generate one. My understanding from the devops team I am working with, is that we could build that call into the entrypoint of the container for one node, but the controller wouldn't necessarily allow that when scaling up and down automatically based on the GitHub actions queue.

@sathishpothuri can you provide any more context?

**Comment by joshua-reddish** [comment]
So to be clear, we want to let the runner call our API, not the GitHub API, we want it to hold the key our API returns for all runner actions until it expires, then grab a new one as needed.

**Comment by mumoshu** [comment]
@joshua-reddish Hey! Thanks for clarifying.

It does sound like a good project for you and your company, but I'm not yet sure what's the benefit for this project to add such API call 🤔 

To make it a as generic as possible feature, the best possible solution I can guess would be adding some additional field to Runner CRD and some enhancement to the runner controller, so that you can point each Runner custom resource to read a K8s secret containing the registration token that an external controller like yours created.

You might add the enhancement here:

https://github.com/actions-runner-controller/actions-runner-controller/blob/a4631f345ba4f0914407e878efbeee65b93253f7/controllers/runner_controller.go#L531-L563

The Runner CRD field to be added would be something like `.spec.registrationTokenFrom.secretKeyRef.{name,key}` that looks very similar to K8s' [env[].valueFrom.configMapKeyRef](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-container-environment-variables-using-configmap-data)

This way, you're basically reusing only the Runner controller contained in actions-runner-controller.

You can still fork this project and add some logic to call your own API from within runner controller. The solution would look very similar to what I described above.

WDYT?
