### ISSUE TITLE
New release 0.18.3?

### ISSUE THREAD

**Issue by zetaab** [actions-runner-controller/actions-runner-controller#562]
There are quite much new PRs merged since 0.18.2. Is it possible that we could make new release 0.18.3 (or 0.19.0)? At least we are currently missing features that is merged, but there are no new release.

Also use new organisation name in new images.

ping @mumoshu

**Comment by toast-gear** [comment]
We're currently discussing how to do releases going forward, we are keen to do another formal release and should be doing one soon.

**Comment by mumoshu** [comment]
@zetaab Hey!

FWIW, we're already working very hard every day to publish the new release ASAP, sacrificing our own spare time. So I think we have nothing constructive thing to do about this issue, as we already know we have to release the next ASAP.

I understand your frustration, but please let me close this to not advocate everyone to repeat a similar action in the future.

If you're willing to help again(btw thanks a lot for #290 :heart: ), #560 is the final blocker for the next release now. The next version is going to be v0.19.0, because we have not only fixes but also many additional features.

#560 would also help accelerating future releases, as we'll be more confident that the next release is rock-solid without taking too much time on manual testing. Currently, it's impossible to cut a new release, for example, after every PR merged. I know that's ideal but that takes too much time testing things manually and repeatedly.

> Also use new organisation name in new images.

I think this worth another dedicated github issue.
DockerHub doesn't allow `-` in the organization name so it's impossible to just migrate to `actions-runner-controller/actions-runner-controller`. What's the best DockerHub org name then? I don't have a good idea yet...

**Comment by mumoshu** [comment]
Some thought #564

**Comment by mumoshu** [comment]
Wrote #566 about the move to a DockerHub organization.
