### ISSUE TITLE
bug: registration-only pods are created with invalid name lengths

### ISSUE THREAD

**Issue by js-timbirkett** [actions-runner-controller/actions-runner-controller#595]
**Describe the bug**
I've seen that registration only pods are created with very long names. This can cause issues when pod names (or RunnerDeployment.Spec.Template.Name) is already fairly long.

Maybe shorten `-registration-only` (which gets prepended to the pod name), or truncate the original pod name before pre-pending `-registration-only`... Or a combination of both?

**Comment by js-timbirkett** [comment]
I'll see if I can dive a bit deeper into this and provide a fix PR / test to cover it.

**Comment by mumoshu** [comment]
@js-timbirkett Good catch! I assume that you're fine to make the original runner deployment name short enough so that the corresponding "regular" runner pods names are still valid, right?

If so, I guess it's better to omit `-registration-only` suffix from the registration-only runner name and instead use some k8s metadata label to differentiate it from regular runners/pods.

More concretely, you might use some label instead of the name here:

https://github.com/actions-runner-controller/actions-runner-controller/blob/cb60c1ec3baed8690d4546dacfdfdc564891e852/controllers/runnerreplicaset_controller.go#L121-L135

And add label rather than tweaking the name on registration-only runner pod's creation:

https://github.com/actions-runner-controller/actions-runner-controller/blob/cb60c1ec3baed8690d4546dacfdfdc564891e852/controllers/runnerreplicaset_controller.go#L155-L169

**Comment by js-timbirkett** [comment]
I was thinking about the runner being given a (runner) label of `registration-only` or something so that it's easy to distinguish in the Github UI. I'll try a few things and see what I can break with some exploration...

**Comment by mumoshu** [comment]
@js-timbirkett Sounds good. Note that the runner label of "the runner resource of GitHub API" is display-purpose-only from the perspective of the controller.

We might need a K8s metadata label on the K8s "Runner" custom resource to distinct it from other standard runners.

Having two enhancements in your patch would be good. But keep in mind not to confuse the two. Sry if you were already aware of that!

**Comment by js-timbirkett** [comment]
A quick "fix" on my side was to use the `adler32sum` function to generate an adler32 hash of the repo name as part of the RunnerDeployment name. Other options would be to use a substring of the sha1 or sha256 hash functions in Helm if using Helm to manage the configuration of Runners or RunnerDeployments.

(This is an informational comment for anyone else who bumps into this problem whilst, or even after a fix has been developed).

**Comment by toast-gear** [comment]
Pinning as we are deprecating the registration-only runners as in theory GitHub are going to be changing their service soon to allow us to scale from 0 without the need for a fake runner.

Pinned issue and added pinned label until this change has gone live.

**Comment by js-timbirkett** [comment]
Closing 🚀
