### ISSUE TITLE
[Question] Updating and deploying custom docker image for runners

### ISSUE THREAD

**Issue by ayk33** [actions-runner-controller/actions-runner-controller#610]
**Question**
Does anyone have a good solution for updating custom runners docker image and safely deploying that without killing all active workflows? Looked through github api to "pause" a workflow but seems like only option is "deactivate" which would not queue up builds.
I'm currently using helm to manage a series of runnerdeployments.

Thanks

**Comment by mumoshu** [comment]
@ayk33 Hey! Still curious but how you confirmed that it kills all active workflows? I thought GitHub runners were able to handle SIGTERM gracefully so that it completes the running workflow job before existing.

Ephemeral runners does have a github-side bug that occasionally prevents graceful termination, racing between the termination process and the dequeuing logic. That might be what you're seeing? If that's the case, I'd suggest trying setting `ephemeral: false` in your runner spec. https://github.com/actions-runner-controller/actions-runner-controller/pull/498

**Comment by ayk33** [comment]
Thank you for the quick response! Let me give this a shot tomorrow and see if that is the bug I'm running into.

**Comment by ayk33** [comment]
Resolved on my end. Thank you!
