### ISSUE TITLE
Consistent versioning

### ISSUE THREAD

**Issue by Kampe** [actions-runner-controller/actions-runner-controller#708]
Hello,

The versions seem to be all over the place, with the latest being close to what the docs provide to use 0.18.2.

I see releases like this month using v 0.12.X

What's going on here?  Where's the disconnect?

**Comment by mumoshu** [comment]
@Kampe Hey! Versions prefixed with `actions-runner-controller-` are chart releases. This was explained in https://github.com/actions-runner-controller/actions-runner-controller/issues/611 before. I admit this is confusing and we're currently trying to migrate all the chart releases to its own github repo so that it becomes less confusing

**Comment by Kampe** [comment]
Aha, gotcha.  Any way to maybe label that?  That could make more sense if context was on the version maybe!
