### ISSUE TITLE
Support for bind-mounting docker socket

### ISSUE THREAD

**Issue by reiniertimmer** [actions-runner-controller/actions-runner-controller#72]
At the moment, runner pods always consist of a `runner` container and a `docker` container (based on dind).

Is it something to consider a configuration setting that would allow the runner to use the bind-mount instead of dind?

While I understand the reason for using dind, it's not always ideal in terms of performance (layer caching, etc) and for some cases you might want to consider mounting `/var/run/docker.sock` directly from the underlying platform.

Default setting could be kept as-is (dind), but setting it to mount the native socket could be added as an extra possiblity.

Does it make sense to have such a setting?

**Comment by summerwind** [comment]
Yes, I think it's a good idea. Auto-starting dind was a good way to increase convenience in the early implementations. However, there are now some problems with using dind.

I'm considering to stop auto-configuring dind by default, and allow users to add it as needed. This would also allow users to use the bind mount.

**Comment by ToonvanStrijp** [comment]
@summerwind is it already possible to mount the `/var/run/docker.sock` from the `hostPath` because this would increase runs because the caching works than... right? Or is it possible to use a shared cache between the `dind` containers?

**Comment by Puneeth-n** [comment]
@mumoshu can you shed some light on if we can use the docker unix socket inside the runner?

**Comment by ToonvanStrijp** [comment]
@Puneeth-n I’m not sure on the kubernetes version 1.20 thing. But I was able to use a mounted docker socket from the node.m. The only problem I had was that it couldn’t mount the runner workspace. So if we could find a way to solve that I would be a great optimisation for me.

**Comment by reiniertimmer** [comment]
I think I can close this issue, since using docker from pods is about to be deprecated anyway. It does not seem to make a whole lot of sense to invest extra time into this.

**Comment by mumoshu** [comment]
Oh sorry I somehow missed this.

This is already possible by just adding volumes and volumeMounts to your runner spec, I think.

The gotcha is though, you need to also bind mount another host path for files sharing "between the runner container and the dockerd host" so that you can use `docker run -v $SOME_PATH`. Does everyone understand this consequence and still wanting to do it? Honestly saying it's hard to believe for me that you thinks this is a practical setup.

**Comment by mumoshu** [comment]
@reiniertimmer For layer caching, @asoldino added `dockerVolumeMounts` to the runner spec https://github.com/actions-runner-controller/actions-runner-controller/issues/435

He uesd "one runner pod per node" in combination with that to safely leverage layer caching.

**Comment by dakar-etoro** [comment]
Hey, I know this PR is closed and I really appreciate your work:))
When I think of implementing this solution it seems unlikely to use one pod per node. I imagine lots of pods running on the same node executing docker build commands or using actions which use docker commands. Layer caching is important to save time. If docker socket is not an option than only the RunnerSet is a suitable solution for that case - which can be also very storage waisting since each pod has its own volume for docker caching. 
Am I Missing something?

Thank you so much!

**Comment by mumoshu** [comment]
@dakar-etoro I think it's technically possible although you need to share not only `/var/run/docker.sock` but also other volume mounts so that you can share files between your runner container and the dockerd running on the host :)

I believe you're not missing anything in terms of the benefit of sharing the dockerd on the host among pods and containers. I just wanted to say that it was more complicated than I had initially thought and probably more complicated than you might have expected. So you'd better implement the layer caching at a different level, like using `actions/cache@v2` on docker buildx cache.

**Comment by toast-gear** [comment]
This isn't a problem actions-runner-controller can help with. You have to either:
- use GitHub's repository caching service

**Comment by dakar-etoro** [comment]
> This isn't a problem actions-runner-controller can help with. You have to either:
> 
> * use GitHub's repository caching service
> * mount volumes and use local cache (actions-runner-controller supports volumes)
> * setup an internal Docker registry cluster using something like this https://github.com/twuni/docker-registry.helm
> 
> Regardless of the solution you go with, it's up to you to implement it

Thanks!
