### ISSUE TITLE
include git-lfs as standard tool

### ISSUE THREAD

**Issue by mad01** [actions-runner-controller/actions-runner-controller#822]
**Is your feature request related to a problem? Please describe.**
We include a very minimal number of tools in the base container. In my opinion we should include git-lfs. In my opinion it feels a bit wrong to have to create a custom image to just have to checkout the code, even if it's using the less common lfs option. 

**Describe alternatives you've considered**
The alternative is to create a custom container image with git-lfs

**Comment by mumoshu** [comment]
@mad01 Hey! I hear you, but sorry we aren't going to support everyone's use-case out of the box because that turned out too much work for us. We aren't getting paid/lack time and resources and therefore we need to be focused on 80% use-cases.

The next best thing would be we maintain a brief guide to help everyone build their own repository and a workflow to automate (re)building a custom runner image based on our default image. But even that sounds like a huge effort for us.

@callum-tait-pbx Thoughts? Would you do it if anyone could sponsor you? 😆

**Comment by toast-gear** [comment]
We've had a think more about this and we're willing to include it in our runner image. The concern we have over including software in general is that it becomes an overhead and all the maintainers have real jobs to do during the day. We're OK with adding this on the assumption that:

1. We have to include the main git binary regardless as the runner is useless without it
2. Git is generally version insensitive
3. The Git config is generally version insensitive

We don't want to go down a path of starting to building in software where the version is important as we don't have the time, energy or resources to really manage that effectively (and so you as a consumer shouldn't want use to go down that route too as you will get an unstable runner image. Furthermore it's often better to install software via an action than it is to bake it into the runner image.

@mad01 Please go ahead and raise a PR for this on all 3 images and test.

**Comment by vmdude** [comment]
@toast-gear As PR has been merged, this issue can be close IMHO.
