### ISSUE TITLE
Skipped jobs scales down runners

### ISSUE THREAD

**Issue by kszymans** [actions-runner-controller/actions-runner-controller#836]
**Describe the bug**

If job skip occurs during workflow execution the `workflow_job`  and `check_run` event returns `workflow_job.status: completed` which causes runners scale down by 1.  

**Checks**

- [x] My actions-runner-controller version (v0.x.y) does support the feature
- [ ] I'm using an unreleased version of the controller I built from HEAD of the default branch

**To Reproduce**

1. Prepare workflow with skipped job
2. Observe the decrement of runners

**Expected behavior**

Scale down runners only when `workflow_job.conclusion` field contains any of these states `[cancelled, success, failure]`

**Screenshots**

**Environment (please complete the following information):**

- Controller Version 0.20.0
- Deployment Method: Helm
- Helm Chart Version 0.13.0

**Additional context**

As I mentioned in expected behavior it should be possible to fix this by verifying `workflow_job.conclusion` and `check_run.conclusion` field content

**Comment by mumoshu** [comment]
@kszymans Hey! Thanks for reporting.

I had expected GitHub to send a workflow_run event of `action=queued` even for an eventually skipped run, but apparently not? Could you confirm that you don't see a workflow_run event with `action=queued` before `action=completed, conclusion=skipped`?

**Comment by mumoshu** [comment]
@kszymans Well I've tried to reproduce this but I was unable to let a workflow job to get skipped. Are you talking about the case that you manually canceled a workflow job while it's running?

**Comment by mumoshu** [comment]
@kszymans I assume you intended to say "Cancelled jobs scales down runners` rather than "Skipped-`. Then I believe this shouldn't be an issue.

When a workflow job is being canceled, actions-runner-controller's webhook server receives two `workflow_job` events. One for `action=queued` and another for `action=completed`. The latter's `conclusion` can be any of `cancelled`, `success`, and `failure`. Regardless of the conclusion, it should scale down the runner added when it received the former, `action=completed` workflow_job event.
