### ISSUE TITLE
Runners are being restarted. Receiving /mutate-runner-set-pod

### ISSUE THREAD

**Issue by lolletsoc** [actions-runner-controller/actions-runner-controller#955]
Hey everyone,

**Environment (please complete the following information):**
Controller Version: 0.20.3
Deployment Method: YAML

We are running v0.20.3 and I've also tried an image built from HEAD.

We are seeing random runner restarts even when they are busy. The controller is logging the following when that happens:
```
2021-11-19T22:23:18.100Z    DEBUG    controller-runtime.webhook.webhooks received request    {"webhook": "/mutate-runner-set-pod", "UID": "5d9fbd86-04a5-46e6-8381-9a1e4948e483", "kind": "/v1, Kind=Pod", "resource": {"group":"","version":"v1","resource":"pods"}}
```
I tried to experiment with the sync-period setting to see if it matched but that didn't lead to anything. Does anyone know in which circumstances we could expect to see the above request come in?

This is likely some form of configuration issue. I appreciate any help!

**Comment by mumoshu** [comment]
@lolletsoc Hey! Could you share more complete logs of actions-runner-controller's contoroller-manager and a few runner pods, so that I can better debug your issue?

At glance, it can be due to an mutating webhook like some service mesh sidecar injector or env/secret injector is trying to mutate the pod managed by actions-runner-controller, that makes me actions-runner-controller think if it needs to recreate the runner pod due to changes.

Also, are you using our webhook-based autoscaler? `workflow_job` based webhook autoscale automatically reduces one runner replica on each workflow job completion. In that case, you are very likely to enable `RUNNER_FEATURE_FLAG_EPHEMERAL` as documented in https://github.com/actions-runner-controller/actions-runner-controller#ephemeral-runners, so that the runner can delay it's termination until the currently running job finishes.

**Comment by lolletsoc** [comment]
Thanks for the reply, @mumoshu and apologies for the delay.

Our problem ended up being nothing to do with the actions runner and instead was a change made to an image streaming feature in our GKE cluster. Once we disabled that, everything worked perfectly!
